name: Deploy Vue App

on:
  push:
    branches:
      - main_old

jobs:
  web-deploy:
    name: Deploy on Every Push
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3

      - name: Prepare Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload files to remote server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          ARGS: "-rlgoDzvc -i --delete --exclude=.htaccess"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
